# 2단 출력

print(2*1, end='')
print(' ', end='')
print(2*2, end='')
print(' ', end='')
print(2*3, end='')
print(' ', end='')
print(2*4, end='')
print(' ', end='')
print(2*5, end='')
print(' ', end='')
print(2*6, end='')
print(' ', end='')
print(2*7, end='')
print(' ', end='')
print(2*8, end='')
print(' ', end='')
print(2*9, end='')
print(' ', end='')