-- 스키마 생성
CREATE TABLE SHOPPING_DATA (
    TIMESTAMP_COLUMN TIMESTAMP PRIMARY KEY,
    PRODUCT_ID VARCHAR2(50),
    PRODUCT_NAME VARCHAR2(100),
    SALES_AMOUNT NUMBER
);

-- 예제 데이터 입력
-- TIMESTAMP_COLUMN: insert문이 실행되는 시점의 날짜와 시간을 저장
INSERT INTO SHOPPING_DATA (TIMESTAMP_COLUMN, PRODUCT_ID, PRODUCT_NAME, SALES_AMOUNT) VALUES (SYSTIMESTAMP, 'P001', '제품1', 1000);
INSERT INTO SHOPPING_DATA (TIMESTAMP_COLUMN, PRODUCT_ID, PRODUCT_NAME, SALES_AMOUNT) VALUES (SYSTIMESTAMP + INTERVAL '1' SECOND, 'P002', '제품2', 1500);
INSERT INTO SHOPPING_DATA (TIMESTAMP_COLUMN, PRODUCT_ID, PRODUCT_NAME, SALES_AMOUNT) VALUES (SYSTIMESTAMP + INTERVAL '2' SECOND, 'P003', '제품3', 2000);
COMMIT;
